# Site settings
title: Ark's tech blog
# email: blog@wtwf.com
description: > # this means to ignore newlines until "baseurl:"
  I sometimes want to link to stuff I find useful or stuff that I've written (of a geeky nature).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wtwf.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  arkarkark
rss: "http://wtwf.com/scripts/atom.xml"

# Build settings
markdown: redcarpet
permalink: /:year/:month/:title.html
